/**
 * SLG API
 * REST API for the New SLG (Novo Sistema de Logística de Gás)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A balance zone
 */
export interface BalanceZone { 
    label?: string;
    country_id?: string;
    vbp_id?: number;
    vbt_id?: number;
    vbs_id?: number;
}

