/**
 * SLG API
 * REST API for the New SLG (Novo Sistema de Logística de Gás)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A contract status
 */
export type ContractStatusType = 'Finished' | 'In force';

export const ContractStatusType = {
    Finished: 'Finished' as ContractStatusType,
    InForce: 'In force' as ContractStatusType
};

