/**
 * SLG API
 * REST API for the New SLG (Novo Sistema de Logística de Gás)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A logistic element type
 */
export type LogisticElementType = 'underground_storage' | 'virtual_balancing_point' | 'regasification_plant' | 'tank' | 'satellite_plant' | 'overseas_transaction_point';

export const LogisticElementType = {
    UndergroundStorage: 'underground_storage' as LogisticElementType,
    VirtualBalancingPoint: 'virtual_balancing_point' as LogisticElementType,
    RegasificationPlant: 'regasification_plant' as LogisticElementType,
    Tank: 'tank' as LogisticElementType,
    SatellitePlant: 'satellite_plant' as LogisticElementType,
    OverseasTransactionPoint: 'overseas_transaction_point' as LogisticElementType
};


