/**
 * SLG API
 * REST API for the New SLG (Novo Sistema de Logística de Gás)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AbstractControl, FormGroup } from "@angular/forms";


/**
 * A balance rule parameter
 */
export interface BalanceRuleParameter { 
    id?: number;
    label?: string;
    value?: number;
    balance_rule_id?: number;
}
export interface BalanceRuleParameterFormGroup extends FormGroup {
    value: BalanceRuleParameter;
    controls: {
    id: AbstractControl;
    label: AbstractControl;
    value: AbstractControl;
    balance_rule_id?: AbstractControl;
      };
  }
